name: Immersive Soundscapes
author: TheWii
version: 2.5.0
minecraft: 1.19
require:
    - bolt
    - bolt_expressions
pipeline:
    - mecha
output: out

data_pack:
    name: "immersive-soundscapes-datapack-v{{project_version}}"
    description: [
        { text: "Immersive Soundscapes", color: "green" },
        { text: "\nv{{project_version}} by {{project_author}}.", color: "dark_gray" }
    ]
    load:
        data: data
        data/thewii/modules/immersive: src
        data/lib/modules: "@beet_plugins/utils"
        pack.png: pack.png

resource_pack:
    name: "immersive-soundscapes-resources-v{{project_version}}"
    description: [
        { text: "Immersive Soundscapes", color: "green" },
        { text: "\nv{{project_version}} by {{project_author}}.", color: "dark_gray" }
    ]
    load:
        assets: assets
        pack.png: pack.png

meta:
    generate_namespace: thewii
    generate_prefix: immersive
    bolt:
        entrypoint: "thewii:*"
    bolt_expressions:
        objective_prefix: "twis."
        init_path: core/objectives
